### PR TITLE
added webpack public path to globals

### PR DESCRIPTION
**Pull request by MarkiyanPyts**

### CODE REVIEW

**Comment by ClaudiuCudla** [comment]
Shouldn't the global item be added at project level?

**Comment by MarkiyanPyts** [comment]
> Shouldn't the global item be added at project level?

Nope this is variable webpack is using for code splitting, to know where to send http requests for chunks.

For projects which is not using code splitting it will not change anything, for ones with it will just not error out at this.

**Comment by ClaudiuCudla** [comment]
> For projects which is not using code splitting it will not change anything, for ones with it will just not error out at this.

But also for projects that don't use webpack at all it will still be there, that's why I think it should be kept per project, only where needed

**Comment by MarkiyanPyts** [comment]
> > For projects which is not using code splitting it will not change anything, for ones with it will just not error out at this.
> 
> But also for projects that don't use webpack at all it will still be there, that's why I think it should be kept per project, only where needed

This will not impact other projects in any way, this global just means to ignore warning for this variable being undefined, webpack adds it on build phase anyway, any project which is using webpack has it available

Also we do not want Leads to overload default config with their own rules that conflicts with Code Review Assistant.

**Pull request closed without merging**
